services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/order_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && 
             python scripts/init_data.py && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: